### PR TITLE
Replace cl with cl-lib for emacs 27

### PR DESCRIPTION
**Pull request by takaxp**
Package cl is deprecated.

### CODE REVIEW

**Comment by half-shell** [comment]
This works for me on GNU Emacs 27.1.
It gets rid of cl package being deprecated, an issue mentioned [here](https://github.com/kiwanami/emacs-epc/issues/35) and [here](https://github.com/hlissner/doom-emacs/issues/3372), with a comment suggesting packages be updated to use `cl-lib` instead of `cl`.

@takaxp Is this still alive? Can we merge this or is there another supported repo that I am not aware of?

**Comment by takaxp** [comment]
`Package cl is deprecated` is still shown even if GNU Emacs 27.1 is used :(

**Comment by stephan-cr** [comment]
As @technician77 correctly points out, there's more work to do. All `cl` functions/macros have the `cl-` prefix in `cl-lib`. `first` needs to be `cl-first`. Right now it seems to work, because something else is loading `cl`.

**Comment by pataquets** [comment]
Looks like this PR is superceded by #22. If there's nothing else here, @takaxp: fancy to close this in favor of #22?

**Pull request closed without merging**
